name: Deploy -> int
  
on:
  workflow_run:
    workflows: ["publish"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: integration_runner
    environment: integration
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          docker --version
          docker-compose --version

      - name: Generate .docker_env file
        run: |
          cat > .docker_env <<EOF
          POSTGRES_HOST=${{ vars.POSTGRES_HOST }}
          SMTP_HOST=${{ vars.SMTP_HOST }}
          REDIS_URL=${{ vars.REDIS_URL }}
          ADMIN_EMAIL=${{ vars.ADMIN_EMAIL }}
          ADMIN_PASS=${{ secrets.ADMIN_PASS }}
          VALHALLA_URL=${{ vars.VALHALLA_URL }}
          POSTGRES_DB=${{ vars.POSTGRES_DB }}
          POSTGRES_USER=${{ vars.POSTGRES_USER }}
          POSTGRES_PASS=${{ secrets.POSTGRES_PASS }}
          SSL_CERT=${{ vars.SSL_CERT }}
          SSL_KEY=${{ vars.SSL_KEY }}
          CONCURRENCY=${{ vars.CONCURRENCY }}
          MAX_CACHE_SIZE=${{ vars.MAX_CACHE_SIZE }}
          HTTP_PROXY=${{ vars.HTTP_PROXY }}
          HTTPS_PROXY=${{ vars.HTTPS_PROXY }}
          NO_PROXY=${{ vars.NO_PROXY }}
          EOF

          cat > .env <<EOF
          DATA_DIR=${{ vars.DATA_DIR }}
          TMP_DATA_DIR=${{ vars.TMP_DATA_DIR }}
          COMPOSE_PROJECT_NAME=${{ vars.COMPOSE_PROJECT_NAME }}
          SSL_CERT_DIR=${{ vars.SSL_CERT_DIR }}
          DOCKER_HOST=unix:///var/run/docker.sock
          EOF

      - name: Pull latest images
        run: |
          docker-compose pull

      - name: Deploy app
        run: |
          docker-compose down --remove-orphans
          docker-compose up -d
          docker image prune -af
